apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: mpc-transformer-apac-production

namespace: mpc-transformer-apac

resources:
  - ../../../kubernetes/base
  - namespace.yaml
  - regional-config.yaml
  - pdpa-compliance.yaml

patchesStrategicMerge:
  - deployment-patch.yaml
  - service-patch.yaml
  - ingress-patch.yaml

configMapGenerator:
  - name: regional-config
    files:
      - regional-settings.yaml
      - pdpa-settings.yaml
      - i18n-settings.yaml

secretGenerator:
  - name: regional-secrets
    files:
      - tls-cert.pem
      - tls-key.pem
      - jwt-secret.key
      - pdpa-encryption.key
    type: kubernetes.io/tls

images:
  - name: mpc-transformer
    newName: ghcr.io/mpc-transformer/secure-mpc-transformer
    newTag: v0.2.0-apac-prod

replicas:
  - name: mpc-transformer
    count: 8

commonLabels:
  environment: production
  region: apac
  tier: production
  compliance: pdpa-privacy

commonAnnotations:
  deployment.kubernetes.io/revision: "1"
  meta.helm.sh/release-name: "mpc-transformer-apac"
  meta.helm.sh/release-namespace: "mpc-transformer-apac"
  region.mpc-transformer.com/primary: "ap-northeast-1"
  region.mpc-transformer.com/secondary: "ap-southeast-1"
  compliance.mpc-transformer.com/pdpa: "enabled"
  compliance.mpc-transformer.com/privacy-act: "enabled"