apiVersion: v1
kind: Service
metadata:
    name: "secure-mpc-transformer-service-production"
    namespace: "secure-mpc-transformer-production"
    labels:
      app: "secure-mpc-transformer"
      environment: "production"
spec:
    selector:
      app: "secure-mpc-transformer"
      environment: "production"
    ports:
      - 
        port: 80
        targetPort: 8080
        protocol: "TCP"
        name: "http"
    type: "LoadBalancer"
