name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out this form to help us understand and reproduce the issue.

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of secure-mpc-transformer are you using?
      placeholder: "v0.1.0"
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: What environment are you running in?
      options:
        - Docker
        - Local Python
        - Kubernetes
        - Other (specify below)
    validations:
      required: true

  - type: dropdown
    id: gpu
    attributes:
      label: GPU Acceleration
      description: Are you using GPU acceleration?
      options:
        - "Yes - CUDA"
        - "No - CPU only"
        - "Yes - Other GPU"
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: "The secure inference fails with..."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Initialize model with '...'
        2. Run inference with '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Relevant error messages or logs (redact any sensitive information)
      render: shell

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Relevant configuration details (redact secrets)
      render: yaml

  - type: checkboxes
    id: security
    attributes:
      label: Security Considerations
      description: Please confirm security aspects
      options:
        - label: I have redacted all sensitive information from logs and config
          required: true
        - label: This bug does not expose cryptographic keys or protocols
          required: true