name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please provide details about your request.

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - "MPC Protocol Enhancement"
        - "GPU Optimization"
        - "New Model Support"
        - "Security Improvement"
        - "Performance Optimization"
        - "Documentation"
        - "Developer Experience"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: "As a researcher/developer, I need..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution
      placeholder: "I would like to see..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered?

  - type: dropdown
    id: complexity
    attributes:
      label: Implementation Complexity
      description: How complex do you think this feature would be?
      options:
        - "Low - Simple configuration change"
        - "Medium - New component or algorithm"
        - "High - Major architectural change"
        - "Unknown"

  - type: checkboxes
    id: requirements
    attributes:
      label: Requirements
      options:
        - label: This feature maintains security guarantees
        - label: This feature is compatible with existing protocols
        - label: I'm willing to contribute to implementation
        - label: I can help with testing