name: Security Vulnerability
description: Report a security vulnerability (use private reporting for critical issues)
title: "[Security]: "
labels: ["security", "vulnerability"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **For critical security vulnerabilities, please use GitHub's private vulnerability reporting or email security@secure-mpc-transformer.org**
        
        This form is for non-critical security improvements and observations.

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe is this vulnerability?
      options:
        - "Low - Minor security improvement"
        - "Medium - Potential security issue"
        - "High - Should use private reporting"
        - "Critical - Should use private reporting"
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which component is affected?
      options:
        - "MPC Protocols"
        - "Cryptographic Implementation"
        - "Network Communication"
        - "Key Management"
        - "GPU Kernels"
        - "Docker Configuration"
        - "Dependencies"
        - "Documentation"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Vulnerability Description
      description: Describe the security issue (avoid disclosing exploits publicly)
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What could an attacker accomplish?
    validations:
      required: true

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: How should this be addressed?

  - type: checkboxes
    id: disclosure
    attributes:
      label: Responsible Disclosure
      description: Please confirm
      options:
        - label: I understand this issue will be publicly visible
          required: true
        - label: I confirm this is not a critical vulnerability
          required: true
        - label: I have not included exploit code or sensitive details
          required: true