apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mpc-transformer
  namespace: mpc-transformer-americas
spec:
  replicas: 6
  template:
    metadata:
      annotations:
        region.mpc-transformer.com/deployment-zone: "americas"
        compliance.mpc-transformer.com/ccpa: "enabled"
        monitoring.mpc-transformer.com/scrape: "true"
    spec:
      nodeSelector:
        topology.kubernetes.io/region: "americas"
        node-type: "gpu-optimized"
        compliance.mpc-transformer.com/approved: "true"
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/gpu"
        operator: "Exists"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/region
                operator: In
                values:
                - "americas"
              - key: compliance.mpc-transformer.com/ccpa-ready
                operator: In
                values:
                - "true"
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - mpc-transformer
            topologyKey: "kubernetes.io/hostname"
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - mpc-transformer
              topologyKey: "topology.kubernetes.io/zone"
      containers:
      - name: mpc-transformer
        env:
        - name: MPC_REGION
          value: "americas"
        - name: MPC_COMPLIANCE_MODE
          value: "ccpa"
        - name: MPC_DATA_RESIDENCY
          value: "americas"
        - name: MPC_LOCALE_DEFAULT
          value: "en-US"
        - name: MPC_TIMEZONE_DEFAULT
          value: "America/New_York"
        - name: MPC_CURRENCY_DEFAULT
          value: "USD"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=mpc-transformer,service.version=0.2.0,deployment.environment=production,region=americas"
        resources:
          requests:
            memory: "24Gi"
            cpu: "8"
            nvidia.com/gpu: 2
          limits:
            memory: "48Gi"
            cpu: "16"
            nvidia.com/gpu: 4
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534
          runAsGroup: 65534
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL